app_user:
    resource: "@AppBundle/Controller/UserController.php"
    type:     annotation

proefles:
    resource: "@ProeflesBundle/Controller/"
    type:     annotation
    prefix:   /

app:
    resource: "@AppBundle/Controller/"
    type:     annotation
# app/config/routing.yml
fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"