<?php

namespace ProeflesBundle\Repository;

/**
 * inschrijvingRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class inschrijvingRepository extends \Doctrine\ORM\EntityRepository
{
}
