<?php

namespace ProeflesBundle\Repository;

/**
 * lessenRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class lessenRepository extends \Doctrine\ORM\EntityRepository
{
}
