<?php

namespace ProeflesBundle\Repository;

/**
 * locatieRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class locatieRepository extends \Doctrine\ORM\EntityRepository
{
}
